[tool.poetry]
name = "eodc-pg-parser"
version = "0.1.0"
description = ""
authors = ["Lukas Weidenholzer <lukas.weidenholzer@eodc.eu>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
networkx = "^2.8.2"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.13.0"
scipy = "^1.8.1"
matplotlib = "^3.5.2"
datamodel-code-generator = {extras = ["http"], version = "^0.12.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
